### ISSUE TITLE
90/180 Day

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#11]
Please add the calculations for 90 day dates as well as 180 day dates to the student tracker. It would also be helpful to have a calculation 30 days out from the 180 day mark so students can be notified by their teacher or advisor that the day is approaching.

**Comment by jb-1980** [comment]
How do you do this in your spreadsheet student tracker? Given a start date, how do you determine what is 90 school days?

**Comment by wmcfarland** [comment]
Github won't let me attach my current teacher tracker. I'll email it to you.

**Comment by jb-1980** [comment]
I have pushed a change to include this feature.

Step 1: Set up your blackout dates by clicking on your name in the upper right hand corner and choosing settings from the dropdown, then clicking on the calendar option in the menu on the settings screen.

Step 2: Feel content that the days in course are showing for student, or optionally change the students' start dates to better reflect when they started the course.

As a bonus,  student that has been in the course >160 days will have their row highlighted in red, and a student who has been in the course > 80 days will have their row highlighted in yellow.

![image](https://cloud.githubusercontent.com/assets/2569898/20364550/c938d93a-ac00-11e6-892a-1cf902cc52f4.png)

If you feel like this addresses your request you can close the issue, or feel free to suggest other enhancements.

/cc @kenburbank @wmcfarland @jsmith1213

**Comment by wmcfarland** [comment]
I'm getting this message after signing out and back in...


Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jb-1980** [comment]
It let's me login, but I have already set blackout dates. Are you able to access this:

[http://student-tracker.gilgenlabs.com/settings/](http://student-tracker.gilgenlabs.com/settings)

**Comment by jb-1980** [comment]
I have pushed another fix that should eliminate that server error.

**Comment by wmcfarland** [comment]
Settings is giving me an internal error...

**Comment by wmcfarland** [comment]
How do I toggle?

**Comment by wmcfarland** [comment]
Ok it's suddenly working

**Comment by jb-1980** [comment]
I am sorry. I should have tested this in its initial state with no blackout dates. That created some bugs I had not seen. But it seems that they have been worked out.

**Comment by wmcfarland** [comment]
Ok. I did my dates. Does it look right? I think it does.

**Comment by wmcfarland** [comment]
Roll over dates are still a problem....

**Comment by wmcfarland** [comment]
I love the color changes!

**Comment by kenburbank** [comment]
Is the number of days in the course calculated using the enrollment date in PS or ELMS?  (Originally, they're supposed to be the same, but we can change the one in ELMS?)  How do we change the start date?

**Comment by kenburbank** [comment]
Regarding the blackout dates.  Can you load the default calendar that has blackout dates which correspond to the school calendar?  Teachers could customize it from there, but I don't understand why they would.

**Comment by jb-1980** [comment]
@kenburbank the number of days is calculated based on the start date, which is set to the value of the initial PS data, and can be altered afterward by the teacher.

You can change the start date by clicking on it, and using the datepicker that appears.

Also, it is entirely possible to load a default calendar of blackout dates, but it took me about a minute to set all the dates for the entire year. So me spending about a day to create a system to save me a minute a year is not high on my priority list. But if it is something that you would like to pursue, you can create an issue for it and I may look into it in the future.

**Comment by kenburbank** [comment]
Re: Calendar - It's more of a training issue than anything, because I assume it will be done for each class individually.  I can hear the moaning, but I agree it's a pretty low priority.

I think you can close this issue.  What say you, Wendy?

**Comment by wmcfarland** [comment]
I'm fine closing it. I went in and worked on my days just fine.
