### ISSUE TITLE
Grade Out Date

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#13]
I noticed that the grade out dates don't reflect the true date I graded a student out on. For example, in Government 1608-11 I graded Aurelia V out today, but the date is marked 12.31.16 (in the future). Can the this tracker accurately show the date I graded out. Sometimes it because an issue.

**Comment by jb-1980** [comment]
It is actually the end date, which is the field from PowerSchool for when the semester ends or some other event like they were dropped from the course, not the graded out date.

It could be possible to include the date. I will just have to explore it. If you want to label this as a feature request I will keep it open for the future.

**Comment by wmcfarland** [comment]
I will once I figure out how to

**Comment by wmcfarland** [comment]
How are you coming on this issue now that you've solved the 90/180 day issue? :)

**Comment by jb-1980** [comment]
Now for the graded out tab the date value is the date of last grade update.
