### ISSUE TITLE
Bug?  Graded out page suddenly shows active students

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#18]
I think it stopped filtering out the -- grades
![image](https://cloud.githubusercontent.com/assets/22966552/20403232/4bb6a786-acbd-11e6-96b6-09cfcb979b98.png)

![image](https://cloud.githubusercontent.com/assets/22966552/20403252/6129db10-acbd-11e6-988c-956de35bd079.png)

**Comment by jb-1980** [comment]
Pushed a fix for this.

**Comment by kenburbank** [comment]
Perfect.  Thanks.
