### ISSUE TITLE
Graded Out Popping Back In

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#24]
I'm noticing that suddenly students who have been graded out are being popped back into my class. Example- Valerie Hay US History A 1608

**Comment by jb-1980** [comment]
Can you export the data as csv, and then send me the file via email?

**Comment by wmcfarland** [comment]
I just graded Emma Hesse out of Digital Photography I today and she popped back in.

**Comment by jb-1980** [comment]
By popped back in, do you mean that she went from the graded out tab to the active tab?

**Comment by wmcfarland** [comment]
As in I graded them out, removed them from the course, and how they're back in the course.

**Comment by jb-1980** [comment]
I think you want to create an issue with ELMS, not with the student tracker.
