### ISSUE TITLE
Missing Students

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#25]
My tracker is missing a ton of students. Will they be added to my Spring 17?

**Comment by jb-1980** [comment]
It is the office, not the tracker. Your students have not been enrolled into the spring term yet. Note that they are missing in your PowerTeacher gradebook as well.

**Comment by wmcfarland** [comment]
I see all in PowerTeacher. Will the start date get fixed or do I manually need to go in and change them?

**Comment by wmcfarland** [comment]
I'm not finding the following student on my student tracker:
![image](https://cloud.githubusercontent.com/assets/23200194/22891376/679f5304-f1cc-11e6-9053-843fbc712cc3.png)
![image](https://cloud.githubusercontent.com/assets/23200194/22891382/6dd3564e-f1cc-11e6-9335-a7852ab5a1ab.png)

**Comment by jb-1980** [comment]
If the student is not in student tracker, than it is highly likely that the student is not enrolled in PS spring semester for that course.

Run the following checks:

- Make sure student is in PowerSchool for semester 2
- Make sure student is not in another tab (dropped or graded out)
- Click on the term to select the 2016 Fall term.

My bet is that he was not re-enrolled in the new semester.

**Comment by wmcfarland** [comment]
I think you're correct.


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________
