### ISSUE TITLE
Just an Enhancement Thought

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#27]
I'm wondering if it would be possible somewhere in the tracker for it to pull the % of ahead or behind.

**Comment by jb-1980** [comment]
Well, it will take some configuration, but I plan on having the most awesomest progress monitoring you have ever laid your eyes on. I just have not been able to focus on this recently. But things are beginning to quite down, so maybe in the next few weeks you should be able to see not just percent ahead/behind, but what assignments have been completed, their mastery level, and probably some other cool bells and whistles.

**Comment by jb-1980** [comment]
Merging with #17
