### ISSUE TITLE
Bulk Email list

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#3]
Add check boxes (on the right perhaps?) for users to generate a semi-colon delimited list of email addresses for bulk mailing. 
Include following features:
- [X] "Select All" option that will just copy all students' emails
- [x] "Include parents" option that will include the parent emails as well as the students
- [ ] Make table to map of advisor emails to the student advisor field, then we can include an "Include advisors" option to add the advisor emails as well.

**Comment by jb-1980** [comment]
As I am reviewing this, it seems we only want to make a list for the active students. Can you think of a reason why we would want to include dropped or graded out students in a mass email?

**Comment by kenburbank** [comment]
No, not really.  Active only is fine with me.

**Comment by jb-1980** [comment]
First feature is complete.
- [X] "Select All" option that will just copy all students' emails

**Comment by kenburbank** [comment]
Feature 1 tested successfully!  Copies only emails in the active table that are processed.  Very nice.

**Comment by jb-1980** [comment]
Second feature is now complete. Guardian emails are now an option to include!
- [x] "Include parents" option that will include the parent emails as well as the students

**Comment by kenburbank** [comment]
Unchecking select all only gives check box for first student listed.

![image](https://cloud.githubusercontent.com/assets/22966552/20066766/fefcd9be-a4cf-11e6-94e3-db3cfea0cc11.png)

**Comment by jb-1980** [comment]
Thanks for pointing out the issue. The material bootstrap theme was not updating correctly when the email list was being generated for the various courses. But it should be working correctly now.
