### ISSUE TITLE
Bug: Application Error When Trying to Log In

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#30]
I can't log into the tracker, nor can I upload an image to show you.

**Comment by jb-1980** [comment]
Looks like there is something going on with the server provider, heroku. I can't even access the application dashboard to analyze the issue. Perhaps heroku was hacked.

good news is that http://gilgenlabs.com:8000/ still works.

**Comment by wmcfarland** [comment]
It won't allow me to access it. Is there a different username and password I need?


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by wmcfarland** [comment]
Could this be why?


http://uproxx.com/technology/amazon-server-outage/

[https://uproxx.files.wordpress.com/2017/02/amazon.jpg?quality=100&w=250]<http://uproxx.com/technology/amazon-server-outage/>

Why An Amazon Outage Is Messing Up The Whole Internet<http://uproxx.com/technology/amazon-server-outage/>
uproxx.com
Amazon is generally seen as a place to get stuff, but its web services are crucial to the internet, and they're struggling to stay up.





[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
> It won't allow me to access it. Is there a different username and password I need?

Not enough antecedents in that sentence to make it clear on what you mean. Is it the site at student-tracker.gilgenlabs.com or gilgenlabs.com:8000 ?

I cannot access http://student-tracker.gilgenlabs.com/ because there is an outage with heroku, could be related to the amazon thing you pointed out.

But I can still access the dev server at http://gilgenlabs.com:8000/

Do you have the same experience, but http://gilgenlabs.com:8000/ won't accept your username and password?

**Comment by wmcfarland** [comment]
I can't not log into Gilgenlabs.


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________
