### ISSUE TITLE
Glitching and Having to Reload

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#32]
@jb-1980 I'm having issues with my student tracker. Some of my students are unable to be unbolded by clicking on them. Also, until I reload I'm unable to switch between courses and tabs. Please Obi Wan....

**Comment by jb-1980** [comment]
OK, I am going to call it the empty course bug. It seems that it wasn't prepared to deal with a course with no active students. But it should be working now.

**Comment by wmcfarland** [comment]
[Recording #13.zip](https://github.com/jb-1980/studenttracker/files/1029614/Recording.13.zip)
Here is what I'm experiencing @jb-1980

**Comment by wmcfarland** [comment]
[Recording #14.zip](https://github.com/jb-1980/studenttracker/files/1030135/Recording.14.zip)
Here is another video of what is happening @jb-1980

**Comment by jb-1980** [comment]
Should be fixed now.

**Comment by wmcfarland** [comment]
I'll let you know if it starts working funky again.


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by wmcfarland** [comment]
Ok. I tried to click on a student's name again and now the information and it's still giving me issues.


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
I need more details. I got that you click on the student's name again and now the information .., and I am wondering what "the information" could be. And what are the issues that it is giving you?

**Comment by wmcfarland** [comment]
When you click on their name, all of their data loads with the email, advisor etc....



Wendy McFarland, M.Ed-
Sequoia Choice Arizona Distance Learning-
480.220.4580


-------- Original message --------

**Comment by jb-1980** [comment]
> When you click on their name, all of their data loads with the email, advisor etc....
Is that not what you are expecting?

**Comment by wmcfarland** [comment]
It's not happening when I click on their name. Only after I reload the page will it work.



Wendy McFarland, M.Ed-
Sequoia Choice Arizona Distance Learning-
480.220.4580


-------- Original message --------

**Comment by jb-1980** [comment]
It must be a special sequence or pattern of clicks, because when I do it everything works as expected. Do you have a specific pattern you can reproduce?

**Comment by wmcfarland** [comment]
That's what I was trying to show you in the video. I had just cleared my cache, reloaded the page and tries to select a student.



Wendy McFarland, M.Ed-
Sequoia Choice Arizona Distance Learning-
480.220.4580


-------- Original message --------
