### ISSUE TITLE
New School Year

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#33]
@jb-1980 will there be a new school year added to the tracker or is it something I need to add myself.

**Comment by jb-1980** [comment]
Just updated it!

**Comment by wmcfarland** [comment]
Thanks! Sorry to bug you day one back from break, but I needed to see who should be graded out!


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
Social Studies Instructor/Title I Coordinator
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________
