### ISSUE TITLE
504 tab

### ISSUE THREAD

**Issue by jb-1980** [jb-1980/studenttracker#39]
Create a feature in student tracker that identifies the 504 students
- [x] The locker_number field should be 504 for students in this category
- [x] Get all students enrolled in one of our school's (120) courses and are 504 and display them to a 504 admin.
- [x] Allow teacher's and 504 admin to mark those students as processed
- [x] Withdrawn students should be filtered from the list of students

/cc @kenburbank @amandasitek @cchleborad

**Comment by kenburbank** [comment]
Create a feature in student tracker that identifies the IEP students

 The locker_number field should be sped or SPED for students in this category

 Get all students enrolled in one of our school's (120) courses and are sped and display them to an IEP admin.

 Allow teacher's and special education admin to mark those students as processed

/cc @kenburbank @amandasitek @cchleborad

**Comment by amandasitek** [comment]
Also add accounts for Amy Stefanisko and Raeann Brittain when/if the SPED option gets created (their roles would be similar to mine for 504, but for SPED notifications instead).

**Comment by jb-1980** [comment]
OK, features for 504 now include no withdrawn students and students are sortable by name, course, and teacher

I will be working on IEP

**Comment by jb-1980** [comment]
OK, so all requested features have been pushed and tested. It seems to work well, but I did have to clear my cache to see the changes.
