### ISSUE TITLE
Data Not Loading Still

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#40]
Even at home, my tracker isn't pulling the data:( @jb-1980

**Comment by jb-1980** [comment]
It appears that you had a student enrolled in your courses without a start date, namely Student Demo. But I have updated the code to account for that, and everything was loading correctly.

**Comment by wmcfarland** [comment]
Yes! It's magically working now!


Why would that make a difference when it hadn't before (asking for a friend😉


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
U.S. History/Government Instructor
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
You can tell your friend that previously the start dates were being stored in a local database and edited by the teacher. But who wants to do that every rollover?

So in the latest version it is all being pulled out of ELMS: the start dates, the blackout dates, the progress. The only thing that is now being stored locally is whether or not you have processed an enrollment (active, dropped, graded out, iep, etc), which is what I wanted to have in the first place because it is easier to maintain.

**Comment by wmcfarland** [comment]
OH! That's amazing! So in July my friend won't have to input the start dates?!


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
U.S. History/Government Instructor
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
Nope! The only thing your friend and everyone else will have to do is check off whether they have processed a student, and the initial configuration of mapping the PowerSchool section to ELMS.
