### ISSUE TITLE
Download student roster?

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#5]
I can already imagine a teacher, (I'll let you imagine who), will say "My only problem is...I use my tracker to do _________."  To head off this problem, could a "Download this roster" button be added to download the info in the selected student records?  I imagine the same format as the proposed  bulk email solution.

That way, whatever columns or sorts the user decides to dream up, they can do it offline of the app.

**Comment by jb-1980** [comment]
So I have made a quick alpha version of this that just exports the PowerSchool data into a csv file. If that is good enough you can close this issue. Otherwise, provide more detail on what features you would like it to have.

**Comment by kenburbank** [comment]
It's perfect,
