### ISSUE TITLE
Clicking on a Student Results in a blank page

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#51]
When I went to send a letter to a student, when I clicked on her name the page was blank. However, I can see other student's information just fine.

**Comment by jb-1980** [comment]
It appears that the student did not have a site or advisor field, and that broke the script as the page was loading.

I just pushed a fix and it should be working now.

**Comment by wmcfarland** [comment]
I think she's a Precision kiddo and most don't. Yesterday, it was working just fine. Maybe your tracker is protesting?


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
U.S. History/Government Instructor
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
Yesterday she didn't need a 75% letter, so that part of the script never executed.

**Comment by wmcfarland** [comment]
I just meant with other Precision kiddos that needed them it had been working FYI.


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
U.S. History/Government Instructor
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________

**Comment by jb-1980** [comment]
I can only assume that the kiddos had an advisor set. Otherwise it would have broken in the same form.
