### ISSUE TITLE
BUG: Unable to View Class Information 

### ISSUE THREAD

**Issue by aavis** [jb-1980/studenttracker#54]
When I click on certain classes in my list, they will no longer load their information. It is hit and miss as to which class is affected. 

[Recording #222.zip](https://github.com/jb-1980/studenttracker/files/2314744/Recording.222.zip)

**Comment by jb-1980** [comment]
I refactored the code to fix the issue with the sites view not working. But I did not correctly change a variable name, so when it tried to sort lists of students in the 504 or iep category it broke. So those courses that don't work have a list of those students.

But I pushed a fix and it is all working now.
