### ISSUE TITLE
BUG: Logs from Logger Not Updating Time in Tutorial I Class

### ISSUE THREAD

**Issue by aavis** [jb-1980/studenttracker#55]
I have a student, J.B., inside of Tutorial I class. She was enrolled as of September 25. She has a number of logs already entered into the Logger. The nightly sync is not entering her time from the Logger into the ELMS class. I will follow this up with an email of screenshots.

**Comment by jb-1980** [comment]
Fixed?

**Comment by aavis** [comment]
Yes, it is.

Thank you,
Angel



[Avis_Staff1]
Mrs. Angel Avis
Middle School English, High School English, and Electives Instructor
Email: aavis@edkey.org
Work Cell: (480) 382-6212
Virtual Classroom Link: http://tinyurl.com/AvisVirtualClassroom
Virtual Tutoring (Individual Help by Appointment): Click here to schedule a time.<https://calendly.com/avisenglish/virtualclassroom>

[sequoia-choice-logo_tree_200r1]
Mission Statem​ent: Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.​

**Comment by eromero2** [comment]
I am having the same issue with a student. The time is not syncing from the tracker to Tutorial. Do you want me to email you the student's info?

There have been several entries that previously synced for this student, but his Time Slot #7 has been stuck at 25/0 for at least a week, maybe 2. There have been several logs in the tracker and no update to his time slot. See below: 

![image](https://user-images.githubusercontent.com/43049923/52749205-b7b96280-2fa5-11e9-8eef-145878f1732e.png)

**Comment by jb-1980** [comment]
The syncing script was corrupted. Should be working now.

**Comment by eromero2** [comment]
Yes, it appears to be working now. Thank you!
