### ISSUE TITLE
New tracker graded out tab

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#60]
Hi,

The ELMS grade column is great.  Nice to have it move the student instantly.

Could you leave the box unchecked when it's moved to the graded out tab.  It will remind me to do the clean up tasks once the class is completed.  Thanks!

**Comment by jb-1980** [comment]
I believe the new changes address this. Could you check and close if it does; otherwise please provide more detail on exactly what you are trying to accomplish.
