### ISSUE TITLE
Additional Filter or User Category

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#67]
What: Tara and I will be co-teaching a few Humanities classes for our data collection courses next year.

Need: Would it be possible to allow the Student Tracker to recognize when there is a "co-teacher" listed in Powerschool in order for the course to appear in our active class lists? Currently, I'm listed as Art History as the co-lead, but because Christin is the TOR these courses only show up in ELMS.

Why should you care @jb-1980?: As more of us are beginning to explore new ways of incorporating cross-curricular classes, this will be a needed filter for Student Tracker to show us all of our classes. I'm guessing Cindy would eventually ask?

**Comment by wmcfarland** [comment]
Any thoughts on how we can get this to work @jb-1980

**Comment by wmcfarland** [comment]
Are you working on this yet???? @jb-1980

**Comment by jb-1980** [comment]
With latest update, you should now be able to have classes you coteach on your StudentTracker. This is opt-in, so do it by clicking the settings:
![image](https://user-images.githubusercontent.com/2569898/64913345-fd343e80-d6f2-11e9-828c-4373c96105f0.png)

Then check that you want to include classes you coteach, and click the update button:
![image](https://user-images.githubusercontent.com/2569898/64913348-1b01a380-d6f3-11e9-9d4a-b5747d74b607.png)

After updating your settings, you will probably want to include the ELMS ids as well to see student progress.

/cc @tbuchanangit, @michellelowman, @kkriley

**Comment by wmcfarland** [comment]
Yas!!!!!!!!! Thank you!

Sent from my iPhone

On Sep 14, 2019, at 1:31 PM, Joseph Gilgen <notifications@github.com<mailto:notifications@github.com>> wrote:


With latest update, you should now be able to have classes you coteach on your StudentTracker. This is opt-in, so do it by clicking the settings:
[image]<https://user-images.githubusercontent.com/2569898/64913345-fd343e80-d6f2-11e9-828c-4373c96105f0.png>

Then check that you want to include classes you coteach, and click the update button:
[image]<https://user-images.githubusercontent.com/2569898/64913348-1b01a380-d6f3-11e9-9d4a-b5747d74b607.png>

After updating your settings, you will probably want to include the ELMS ids as well to see student progress.

/cc @tbuchanangit<https://github.com/tbuchanangit>, @michellelowman<https://github.com/michellelowman>, @kkriley<https://github.com/kkriley>

**Comment by michellelowman** [comment]
[Image]





Michelle Lowman, CPM
Elementary Support Specialist
Sequoia Choice, Arizona Distance Learning
Phone: 602.469.4436

Main Office: 480.461.3222
Fax: 480.890.4106
calendly.com/mlowman

"Education is the most powerful weapon which you can use to change the world." ~ Nelson Mandela


________________________________
