### ISSUE TITLE
BUG: No 2019-2020 Term Available in "Select term" Drop Down List

### ISSUE THREAD

**Issue by aavis** [jb-1980/studenttracker#68]
I am currently logged into the Student Tracker. I have new students being enrolled in the 2019-2020 sections of my courses; however, I cannot see them because there is no 2019-2020 section available in the “Select term” drop down list.

Can this be added please?

Thank you,
Angel

**Comment by jb-1980** [comment]
Done! But, it seems the 2019-2020 enrollments are sparse at best. Issue outside of StudentTracker.
