### ISSUE TITLE
BUG: Unable to Access 2018-2019 Term

### ISSUE THREAD

**Issue by aavis** [jb-1980/studenttracker#70]
Good morning!

I am not able to access my information in the 2018-2019 term. It only spins when I try to access the term. No classes will load. 

Thanks,
Angel

**Comment by jb-1980** [comment]
I am seeing the same thing. It is intermittent, but the issue is that after 30 seconds the server closes the connection. I don't know if the bottle neck is with ELMS or PowerSchool, but one is taking to long to return the data.
