### ISSUE TITLE
Blank Data in Tracker

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#74]
I have some students who are missing start dates and a site. Where would one get this fixed @jb-1980 
![image](https://user-images.githubusercontent.com/23200194/65531316-729bce00-deae-11e9-9f14-c364e1107890.png)

**Comment by jb-1980** [comment]
This data is pulled directly from ELMS. The value for the `enrollmentDate` field is `null` in the data from ELMS. Note that you will see a similar issue if you look at one of these students in the ELMS progress report. There will be no enrollment date as there is for other students.

The only way I know of to get it fixed is let E3 know that these students are not showing and enrollment date in their progress report. Check them out at https://myedkey.org/grades/#/
