### ISSUE TITLE
Students included that wouldn't normally qualify

### ISSUE THREAD

**Issue by JHullenaar** [jb-1980/studenttracker#77]
I'm noticing we are getting some students appearing in the SST Manager that wouldn't normally qualify for the process.  Per Joseph, some kids are being kept in because they were in a previous cycle (not kids picked up by a mentor, improved on their own so would no longer qualify).  We are also seeing new kids included because the initial grade in a class when no work has been due or submitted yet is an "F".

**Comment by jb-1980** [comment]
Please post at https://github.com/SequoiaChoice/sst-manager/issues
