### ISSUE TITLE
SST Manager shows 1 student for 45 day list, but no students come up on the list

### ISSUE THREAD

**Issue by JHullenaar** [jb-1980/studenttracker#78]
For the ECK 11-12 group, the manager/tracker shows we have one identified 45 day screening student, but when we click on that to see the list, no one is listed.
![ECK 11-12 Screenshot 11-26-19](https://user-images.githubusercontent.com/25617660/69662007-be9af880-1040-11ea-9afd-9364a3a8bb92.png)

**Comment by jb-1980** [comment]
Wrong repository. You want https://github.com/SequoiaChoice/sst-manager/issues
