### ISSUE TITLE
Graded out tab includes IP from last semester

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#8]
I posted an IP for Rino Nakayama at the end of last semester for Intro to Culinary Arts.  The current term has no grade posted and I still have her in the course.  I suppose an IP should be filtered into active the same as the -- grade.

![image](https://cloud.githubusercontent.com/assets/22966552/19665408/bc959dee-99f9-11e6-9572-82d00d0e9438.png)

**Comment by jb-1980** [comment]
I actually think it is better that the IP should be in the Graded Out tab. My reasoning is that at the end of every semester we have to do roll over. I know that I am done with my rollover when I no longer have any students in the Active tab.

The rollover is supposed to force students into a new section. (That is part of what is causing issues with new start dates). So an IP from the previous semester should disappear when coming into the current semester. The students should all become active again with each new semester.

When looking at the [grades file](http://student-tracker.gilgenlabs.com/api/v1/grades/2601) you can search for 29526 (the student record id) and there are 4 entries for the sectionid 24611 (culinary arts). The IP was given on 07-11-2016, after the start of the semester.

I think if you don't want the student in the Graded Out tab, the better practice is to remove her grade from the gradebook. I see that you mentioned that the current term has no grade posted, but I am seeing a grade posted from the record in the grades table.

**Comment by kenburbank** [comment]
I completely agree.  I thought this IP looked back to last semester, but then I found the email about a strange glitch in PowerTeacher which I will forward.  I think Jeanine did post that IP this semester in response, and your comment above is the procedure teachers should follow.  Thanks.
