### ISSUE TITLE
Checkmarks disappear in certain special cases

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#9]
Hi,

I can check off these few students as processed in the active table, log out, and they will be unchecked when I log back in:

Bona, Ashley         132082  MFL A  
Espinoza, Mariah  129639  MFL A  
Bongliogatti, Victoria  134660   Financial Literacy 1
Rodruguez, Alexandra  133300   Financial Literacy 2

A little research on each.  I can't find a common denominator. 

Bona:  Enrolled 6/1/16 and given an IP at 6/30.  Does not appear in any other table.

Espinoza:  Enrolled 6/14 and given an IP on 6/30.  W/D from school on 8/10 and returned 9/6.  She also appears in the dropped table with a --.

Bongliotti:  Enrolled 9/6, never prior, still active. W/D from school on 8/10 and returned 9/6. She also appears in the dropped table with a --.

Rodriguez: Enrolled 8/22, never prior.  Retained per PS transfer info.   Does not appear in any other table. 

![image](https://cloud.githubusercontent.com/assets/22966552/19744968/9f16a790-9b84-11e6-9bdf-180c199de2ea.png)

**Comment by kenburbank** [comment]
Forgot to mention, I do have other students that enrolled last semester, received IPs, but are not presenting this issue.

**Comment by jb-1980** [comment]
All students had '--' as the final grade in the PS pgfinalgrades table. I had the logic to handle it on the front end, but not on the server. They are now correctly displaying as processed.
